"""all models

Revision ID: aa2774a7c249
Revises: 
Create Date: 2026-04-03 10:59:35.741649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa2774a7c249'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('chief', 'member', name='role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('expeditions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chief_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'ready', 'active', 'finished', name='expeditionstatus'), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chief_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_expeditions_chief_id'), 'expeditions', ['chief_id'], unique=False)
    op.create_index(op.f('ix_expeditions_created_at'), 'expeditions', ['created_at'], unique=False)
    op.create_table('expedition_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('expedition_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.Enum('invited', 'confirmed', name='memberstate'), nullable=False),
    sa.Column('invited_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['expedition_id'], ['expeditions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('expedition_id', 'user_id', name='uq_expedition_user'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_expedition_members_expedition_id'), 'expedition_members', ['expedition_id'], unique=False)
    op.create_index(op.f('ix_expedition_members_user_id'), 'expedition_members', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expedition_members_user_id'), table_name='expedition_members')
    op.drop_index(op.f('ix_expedition_members_expedition_id'), table_name='expedition_members')
    op.drop_table('expedition_members')
    op.drop_index(op.f('ix_expeditions_created_at'), table_name='expeditions')
    op.drop_index(op.f('ix_expeditions_chief_id'), table_name='expeditions')
    op.drop_table('expeditions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
